language: node_js
node_js:
  - 10
  - 12
  - 14
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn all
  - yarn test
  - yarn report-coverage
deploy:
  skip_cleanup: true
  provider: npm
  email: li0liq@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true